version: '3'

tasks:
  install:
    deps:
      - build
    cmds:
      - ln -sf $(pwd)/plugins/github.sh ${HOME}/Library/Application\ Support/xbar/plugins/github.30s.sh
  build:
    deps:
      - build-github
    cmd: go build -ldflags "-s -w -X 'github.com/koki-develop/xbar-plugins/cmd.githubToken=$(gh auth token)'" .
  build-github:
    cmds:
      - |
        cat << EOF > plugins/github.sh
        #!/bin/bash

        $(pwd)/xbar-plugins github
        EOF
      - chmod +x ./plugins/github.sh
